name: Daily Shorts
on:
  schedule:
    - cron: '0 0 * * *'       # UTC0:00 → JST9:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      - name: Install deps & ffmpeg
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ffmpeg
          npm ci --omit=dev

      # ───── body.mp4 を生成 ─────
      - name: Generate body.mp4
        run: node scripts/generate_body.js

      # ───── intro + body + cv を結合 ─────
      - name: Concat intro+body+cv
        run: |
          ffmpeg -y \
            -i assets/intro.mp4 -i assets/body.mp4 -i assets/cv.mp4 \
            -filter_complex "[0:v][1:v][2:v]concat=n=3:v=1:a=0,format=yuv420p[v]" \
            -map "[v]" -t 41 final.mp4   # 36+2.5+2.5 ≒ 41s

      # ───── YouTube Shorts アップロード ─────
      - name: Upload to YouTube Shorts
        env:
          YT_ACCESS_TOKEN: ${{ secrets.YT_ACCESS_TOKEN }}
          VIDEO_TITLE: "ささきや茶房 #Bonfilet #チーム #カルチャー"
        run: node scripts/upload.js
