name: Daily Shorts

on:
  schedule:
    - cron: '0 0 * * *'   # UTC 0:00 = JST 9:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. コードを取ってくる
      - uses: actions/checkout@v4

      # 2. Node.js をセットアップ
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. 必要なパッケージをインストール
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          npm install --no-audit --no-fund

      # 4. Refresh Token → Access Token を生成
      - name: Get new access token
        run: |
          TOK=$(curl -s \
            -d client_id=$YT_CLIENT_ID \
            -d client_secret=$YT_CLIENT_SECRET \
            -d refresh_token=$YT_REFRESH_TOKEN \
            -d grant_type=refresh_token \
            https://oauth2.googleapis.com/token | jq -r .access_token)
          echo "YT_ACCESS_TOKEN=$TOK" >> $GITHUB_ENV
        env:
          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}

      # 5. body.mp4 を生成
      - name: Generate body.mp4
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npm run gen

      # 6. intro + body + cv を結合
      - name: Concat intro+body+cv
        run: npm run concat

      # 7. YouTube Shorts にアップロード
      - name: Upload to YouTube Shorts
        env:
          YT_ACCESS_TOKEN: ${{ env.YT_ACCESS_TOKEN }}
          VIDEO_TITLE: "カルチャーハックメディア｜${{ github.event_name }}"
        run: npm run upload
